server:
  port: 8080
spring:
  application:
    name: bootiful-gateway
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE:http://localhost:9090}

management:
  endpoints:
    web:
      exposure:
        include: "*"